version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-ghosthire}
    networks:
      - backend-net
    restart: always

  redis:
    image: redis:7-alpine
    networks:
      - backend-net
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME:-user}/ghosthire-backend:latest
    # build:
    #   context: .
    #   dockerfile: docker/backend.prod.Dockerfile
    command: [ "/bin/bash", "scripts/entrypoint.sh", "backend" ]
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-ghosthire}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - backend-net
    depends_on:
      - db
      - redis
    restart: always

  worker:
    image: ${DOCKERHUB_USERNAME:-user}/ghosthire-backend:latest
    command: [ "/bin/bash", "scripts/entrypoint.sh", "worker" ]
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-ghosthire}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - backend-net
    depends_on:
      - db
      - redis
    deploy:
      mode: replicated
      replicas: 2
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME:-user}/ghosthire-frontend:latest
    networks:
      - backend-net
    restart: always

  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/conf.d/default.conf
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    networks:
      - backend-net
    depends_on:
      - backend
      - frontend
  # Basic Monitoring
  # prometheus: ...
  # grafana: ...

networks:
  backend-net:


volumes:
  postgres_data:
